### ISSUE TITLE
Poprawić SVG sprite

### ISSUE THREAD

**Issue by KitsuneAkvma** [KitsuneAkvma/tankteam-project-1#28]
W  **sprite.svg** mamy problem z ostatnimi trzema pozycjami.

![obraz](https://user-images.githubusercontent.com/106407746/188290367-80f0d96b-d850-402b-8c5c-fb9f61fd3c4b.png)

Jak widać nie wygląda to poprawnie, tak samo nie działa to dobrze. 

![obraz](https://user-images.githubusercontent.com/106407746/188290407-bd9af92b-9099-4216-8170-0dbf0e31cdd3.png)

 SVG powinno wyglądać mniej więcej w ten sposób.  Najważniejsze jest, żeby poprawić `#icon-arrow`, ze względu na to ile razy jest użyte na stronie, dodatkowo np @kwiatkowsko  nie jest wstanie dokończyć swojej sekcji bez tego. 

Co do `#icon-burger` i `#icon-close` to kwestia poboczna bo możemy zrobić to pseudo-elementami, ale czy chce wam się z tym bawić ? 

Polecam te strony do szukania ikonek : 
https://heroicons.com/
https://boxicons.com/
https://icomoon.io/ (wiadomo ułatwia tworzenie sprite)
https://www.svgrepo.com/ (ale ciężko się połapać tutaj xD)

Także do poprawy jest SVG :

- `#icon-arrow`
- `#icon-burger`
- `#icon-close`

**Comment by MalgorzataMarczynska** [comment]
Pod icon-arrow jest już właściwa strzałka, dzióbek to chevron, jest icona burgera i zamknięcia.
