### ISSUE TITLE
Poprawki w hero

### ISSUE THREAD

**Issue by KitsuneAkvma** [KitsuneAkvma/tankteam-project-1#30]
Layout sekcji Hero #17  jest strasznie rozjechany. 
![obraz](https://user-images.githubusercontent.com/106407746/188290942-bc29866d-c806-425b-a522-cd008b0e5c46.png)

- Odległość blokowa (pionowa) jest ogromna, co nie zgadza się z makietą,
- Brakuje okręgu w tle louda. Najlepiej będzie to rozwiązać albo za pomocą `radial-gradient()`
![obraz](https://user-images.githubusercontent.com/106407746/188291026-b2486e90-7e23-4a87-bb3e-bca52712c74d.png)

albo przy pomocy dodatkowego `<div class="samle__circle">` z pozycją `absolute`,  `.sample_circle { z-index:-1;}` a dla loda `z-index:1;`

- Logo jest stanowczo za małe, a burger powinien być  koloru `$accent`
![obraz](https://user-images.githubusercontent.com/106407746/188291336-c4d8ec71-0893-46ef-8438-95e48c5e9598.png)

- linki przycisków można podpiąć pod sekcje, żeby od razu przewijało użytkownikowi np do produktów.

- Nie pasuje mi pozycja louda. jak się przyjrzysz to tekst bardziej nachodzi na louda. Ale to już szczegół 😉
![obraz](https://user-images.githubusercontent.com/106407746/188291311-d005d357-e77b-4d89-a528-63643e17dde8.png)

**Comment by DorotaDomanska** [comment]
Co do odległości pionowej, poziomej i layout, to makieta jest zaprojektowana na 320x502. Jeśli tak sobie ustawisz w devtoolsach, to zobaczysz, że wszystko się zgadza.

Elipsę zostawiam sobie na potem...może dziś, a może na koniec. Zobaczę jak się będę wyrabiać.

Logo jest takie jak w makiecie i jest wstawionym .png (przygotowanym przez Agatę).
Burger się nie koloruje, bo svg są złe i nadal mają fill.
