### ISSUE TITLE
@MalgorzataMarczynska potrzebny review do drobnych poprawek, po tym rebase @KitsuneAkvma, bo weszły zmiany od czasu questa i zmiana na **dev**, wtedy można puszczać

### ISSUE THREAD

**Issue by kwiatkowsko** [KitsuneAkvma/tankteam-project-1#32]
@MalgorzataMarczynska potrzebny review do drobnych poprawek, po tym rebase @KitsuneAkvma, bo weszły zmiany od czasu questa i zmiana na **dev**, wtedy można puszczać

_Originally posted by @kwiatkowsko in https://github.com/KitsuneAkvma/tankteam-project-1/issues/31#issuecomment-1236283195_

**Comment by KitsuneAkvma** [comment]
Rebase poszedł, znowu mi nie zpushowało zmian na githuba. Prosiłbym  o sprawdzenie i merge

**Comment by KitsuneAkvma** [comment]
Dobra wszystko bez konfliktów, śmiga elegancko więc zamykam issue
