### ISSUE TITLE
feature/Reviews  testimonials Slider

### ISSUE THREAD

**Issue by KitsuneAkvma** [KitsuneAkvma/tankteam-project-1#40]
Nie mogę ogarnąć jak odpalić splide dla komentarzy. Nie wiem czy jest taka możliwość więc biorę się za pisanie JS postaram się, wyrobić. raczej prosta sprawa, gorzej zrobić, żeby to się samo zmieniało .

**Comment by kwiatkowsko** [comment]
może zamiast, żeby samo się zmieniało to te kropki zrobić na buttony -> tak szybka manulana wersja, ew. później kombinować z samoistnym ruchem?
