### ISSUE TITLE
Potrzebne poprawki w products

### ISSUE THREAD

**Issue by kwiatkowsko** [KitsuneAkvma/tankteam-project-1#48]
![image](https://user-images.githubusercontent.com/96976740/188441113-92aa13b6-45ee-4a76-8040-c2adfb6669ca.png)

-potrzebne jest ograniczenie szerokości products__description, 
-coś dziwnego stało się z .products__name, że jest bardzo rozmazany i nieczytelny 
-trzeba wymyślić sposób na zdjęcia w pseudoelementach, ponieważ jakość bardzo spadła.

**Comment by AgnieszkaBaranowska** [comment]
"potrzebne jest ograniczenie szerokości products__description" -- >Poprawiłam to pisząc wersje na tablet 
"coś dziwnego stało się z .products__name, że jest bardzo rozmazany i nieczytelny" --> Tutaj miałam źle zaciągnięty font-weight już też poprawione

**Comment by KitsuneAkvma** [comment]
Potwierdzam, opisy i nazwy są poprawione. Zdjęcia raczej musimy tak  zostawić. Jakby zależało im na jakości to byśmy nie musieli przez squoosha puszczać ich. Ewentualnie ktoś mógłby oryginał puścić przez squoosha ale z naprawdę minimalną stratą .
